#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fabric-org2
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-org2
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: couchdb-org2-peer1
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-org2-couchdb
  resources:
    requests:
      storage: 1Gi
