#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
---
apiVersion: batch/v1
kind: Job
metadata:
  name: job-scrub-fabric-volumes
spec:
  backoffLimit: 0
  completions: 1
  template:
    metadata:
      name: job-scrub-fabric-volumes
    spec:
      restartPolicy: "Never"
      containers:
        - name: main
          image: busybox:latest
          command:
            - sh
            - -c
            - "rm -rvf /mnt/fabric-*/*"
          volumeMounts:
            - name: fabric-org1-ca-volume
              mountPath: /mnt/fabric-org1-ca
            - name: fabric-org1-peer1-volume
              mountPath: /mnt/fabric-org1-peer1
            - name: fabric-org1-peer2-volume
              mountPath: /mnt/fabric-org1-peer2
            - name: couchdb-org1-peer1-volume
              mountPath: /mnt/fabric-couchdb-org1-peer1
            - name: couchdb-org1-peer2-volume
              mountPath: /mnt/fabric-couchdb-org1-peer2
      volumes:
        - name: fabric-org1-ca-volume
          persistentVolumeClaim:
            claimName: fabric-org1-ca
        - name: fabric-org1-peer1-volume
          persistentVolumeClaim:
            claimName: fabric-org1-peer1
        - name: fabric-org1-peer2-volume
          persistentVolumeClaim:
            claimName: fabric-org1-peer2
        - name: couchdb-org1-peer1-volume
          persistentVolumeClaim:
            claimName: couchdb-org1-peer1
        - name: couchdb-org1-peer2-volume
          persistentVolumeClaim:
            claimName: couchdb-org1-peer2
